services:
  stats-server:
    build:
      context: ./stats-server/server
      dockerfile: Dockerfile
    image: stats-server
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - statdb
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://statdb:5432/statdb
      - SPRING_DATASOURCE_USERNAME=ewm
      - SPRING_DATASOURCE_PASSWORD=ewm
      - JAVA_OPTS=-Djdk.httpclient.HttpClient.log=errors,requests

  statdb:
    image: postgres:14-alpine
    volumes:
      - ./pgdata/statdb:/var/lib/postgresql/data
    container_name: statdb
    environment:
      - POSTGRES_DB=statdb
      - POSTGRES_USER=ewm
      - POSTGRES_PASSWORD=ewm

  ewm-service:
    build:
      context: ./ewm-service
      dockerfile: Dockerfile
    image: ewm-service
    container_name: ewm-service
    ports:
      - "8080:8080"
    depends_on:
      - ewmdb
      - stats-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewmdb:5432/ewmdb
      - SPRING_DATASOURCE_USERNAME=ewm
      - SPRING_DATASOURCE_PASSWORD=ewm
      - SERVICES_STATSSERVICE_URI=http://stats-server:9090
    #   - JAVA_OPTS=-Djdk.httpclient.HttpClient.log=errors,requests

  ewmdb:
    image: postgres:14-alpine
    volumes:
      - ./pgdata/ewmdb:/var/lib/postgresql/data
    container_name: ewmdb
    environment:
      - POSTGRES_DB=ewmdb
      - POSTGRES_USER=ewm
      - POSTGRES_PASSWORD=ewm
